name: Package Push Nuget
on:
  release:
    types: [ created ]

jobs:
  packeg-build:
    name: package build and push
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v2
    - name: run a one-line script
      run: env
    - name: setting dotnet version 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: package push
      run: |
        env
        echo "------------------------------------------------------"
        ls
        dotnet build
        dotnet pack  --include-symbols  -p:PackageVersion=$GITHUB_REF_NAME
        dotnet nuget push "**/*.symbols.nupkg" -k  ${{secrets.NUGET_TOKEN}}  -s https://api.nuget.org/v3/index.json
        
