name: Package Push Github
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  package-push:
    name: package build and push
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: setting dotnet version 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --no-restore 

    - name: pack
      run: dotnet pack --include-symbols  -p:PackageVersion=0.0.$GITHUB_RUN_ID 
      
    - name: package push
      run: dotnet nuget push "**/*.symbols.nupkg"  --api-key ${{secrets.PACKAGE_NUGET_GITHUB}}  --source https://nuget.pkg.github.com/masastack/index.json
